
export PATH=~/.local/bin:$PATH
export LANG=ru_RU.UTF-8
export VOICEMAN_EMACSPEAK_RATE_FRACTION=2

if ! [ -e /tmp/voiceman.socket ]; then
    voicemand -d
fi

setxkbmap -layout "us,ru"
setxkbmap -option "grp:ctrl_shift_toggle,grp_led:scroll"

exec dwm-luwrain
