#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

THIS="${0##*/}"

[ -z "$1" ] && echo "ERROR: THIS: No destination distro" >&2 && exit 1
DISTRO="$1"

mkdir -p out
docker run --rm -i -v "$(pwd)/out:/out" "$DISTRO" bash -c 'apt-get update && \
apt-get install -y --no-install-recommends git g++ build-essential debhelper ca-certificates  openjdk-17-jdk openjfx ant maven wget timidity fluid-soundfont-gm sox midicsv locales locales-all g++ zlib1g-dev libssl-dev gperf cmake && \
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64 && \
export JAVA_INCLUDE_PATH=$JAVA_HOME/include && \
export LANG=ru_RU.UTF-8 && \
git clone https://github.com/tdlib/td/ && \
cd td && \
git checkout v1.8.0 && \
mkdir jnibuild && cd jnibuild && \
cmake -DCMAKE_BUILD_TYPE=Release -DTD_ENABLE_JNI=ON -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td .. && \
cmake --build . --target install && \
cd ../example/java && \
mkdir build && cd build && \
cmake -DCMAKE_BUILD_TYPE=Release -DTd_DIR=/td/example/java/td/lib/cmake/Td -DCMAKE_INSTALL_PREFIX:PATH=.. .. && \
cmake --build . --target install && \
cd ../../../.. && \
mkdir -p /org/luwrain/jni/Linux/64 && \
cp -r /td/example/java/bin/libtdjni.so /org/luwrain/jni/Linux/64 && \
touch /org/luwrain/jni/Linux/64/autoload.txt && \
jar cvf luwrain-jni.jar org/luwrain/jni/Linux/64/* && \
git clone --recursive https://github.com/luwrain/parent luwrain && \
cd luwrain && \
cd base/sounds && \
./make && \
cp *.wav ../../luwrain/src/main/resources/org/luwrain/core/sound/ && \
cd ../scripts && \
./lwr-build && \
./lwr-dpkg-snapshot && \
cd ../.. && \
cp /luwrain-jni.jar release/jar/ && \
dpkg-buildpackage --build=binary -us -uc && \
mv /*.deb /out/'
