#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

THIS="${0##*/}"

[ -z "$1" ] && echo "ERROR: THIS: No destination distro" >&2 && exit 1
DISTRO="$1"
[ -z "$GPG_KEYS" ] && echo "ERROR: $THIS: No the GPG_KEYS variable" >&2 && exit 1

cat apt.config > out/apt.config
docker run --rm -v "$(pwd)/out:/out" -v "$GPG_KEYS:/gpg:ro" "$DISTRO" bash -c 'apt-get update && \
apt-get install -y --no-install-recommends ca-certificates dpkg-dev apt-utils gnupg2 && \
DIST=$(grep VERSION_CODENAME /etc/os-release | sed -e s/^.*=//) && \
cd /out && \
sed -i -e s/SUBST_CODENAME/$DIST/ apt.config && \
mkdir /root/.gnupg && chmod 700 /root/.gnupg && \
cp /gpg/gpg*.conf /root/.gnupg && \
gpg --batch --no-tty --import /gpg/dpkg.key && \
rm -rf dists/$DIST && \
mkdir -p dists/$DIST/luwrain/binary-amd64 && \
cp *.deb dists/$DIST/luwrain/binary-amd64 && \
dpkg-scanpackages dists/$DIST/luwrain/binary-amd64 /dev/null > dists/$DIST/luwrain/binary-amd64/Packages && \
cd dists/$DIST && \
apt-ftparchive release -c ../../apt.config . > Release && \
gpg --default-key info@luwrain.org --clearsign --passphrase-fd 0 -o InRelease Release < /gpg/passwd'

rm out/apt.config 
