#!/bin/bash -evx
# SPDX-License-Identifier: BUSL-1.1
# Copyright 2012-2026 Michael Pozhidaev <msp@luwrain.org>

DIR="$(pwd)"
if [ -d "$DIR/debian/luwrain-snapshot" ]; then
    DEST_DIR="$DIR/debian/luwrain-snapshot/usr/share/luwrain"
    BIN_DIR="$DIR/debian/luwrain-snapshot/usr/bin"
    APP_DIR="$DIR/debian/luwrain-snapshot/usr/share/applications"
else
    DEST_DIR="$DIR/debian/luwrain/usr/share/luwrain"
    BIN_DIR="$DIR/debian/luwrain/usr/bin"
    APP_DIR="$DIR/debian/luwrain/usr/share/applications"
fi

mkdir -p  "$DEST_DIR" "$DEST_DIR/bin" "$BIN_DIR" "$APP_DIR"

cp -r lib js luwrain.ico "$DEST_DIR"
cat <<EOF > "$DEST_DIR/bin/luwrain"
#!/bin/bash -e
# SPDX-License-Identifier: BUSL-1.1
# Copyright $(date +%Y) Michael Pozhidaev <msp@luwrain.org>

if [ -z "\$SPEECHD_HOST" ]; then
    export SPEECHD_HOST=localhost
fi

if [ -z "\$SPEECHD_PORT" ]; then
    export SPEECHD_PORT=6560
fi

cd /usr/share/luwrain/lib
exec java -cp luwrain-base.jar \
     org.luwrain.core.Init \
     --app-dir /usr/share/luwrain \
     --def-speech speechd \
     "\$@"
EOF

cat <<EOF > "$DEST_DIR/bin/lwr"
#!/bin/bash -e
# SPDX-License-Identifier: BUSL-1.1
# Copyright $(date +%Y) Michael Pozhidaev <msp@luwrain.org>

exec luwrain "\$@" > /dev/null 2>&1
EOF
chmod 755 "$DEST_DIR/bin/luwrain" "$DEST_DIR/bin/lwr"

ln -s /usr/share/luwrain/bin/luwrain "$BIN_DIR/luwrain"
ln -s /usr/share/luwrain/bin/lwr "$BIN_DIR/lwr"
cp luwrain.desktop "$APP_DIR"
