#!/bin/bash -e
# SPDX-License-Identifier: BUSL-1.1
# Copyright 2026 Michael Pozhidaev <msp@luwrain.org>

NAME=done

cat <<EOF > $NAME.csv
0, 0, Header, 1, 6, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 85"
2, 0, Program_c, 1, 85
2, 0, Note_on_c, 1, 71, 96
2, 60, Note_off_c, 1, 71, 0
2, 60, Note_on_c, 1, 76, 96
2, 120, Note_off_c, 1, 76, 0
2, 120, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 85"
3, 0, Program_c, 2, 85
3, 60, Note_on_c, 2, 80, 96
3, 120, Note_off_c, 2, 80, 0
3, 120, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 106"
4, 0, Program_c, 3, 106
4, 60, Note_on_c, 3, 80, 84
4, 120, Note_off_c, 3, 80, 0
4, 120, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 108"
5, 0, Program_c, 4, 108
5, 0, Note_on_c, 4, 40, 84
5, 60, Note_off_c, 4, 40, 0
5, 60, Note_on_c, 4, 64, 84
5, 120, Note_off_c, 4, 64, 0
5, 120, End_track
6, 0, Start_track
6, 0, Instrument_name_t, "MIDI instrument 95"
6, 0, Program_c, 5, 95
6, 0, Note_on_c, 5, 52, 60
6, 120, Note_off_c, 5, 52, 0
6, 120, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -a -C 8 -s 256000 -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox -D $NAME.wav -c 1 -e float .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 50 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.1 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav

