#!/bin/bash -e

NAME=error

cat <<EOF > $NAME.csv
0, 0, Header, 1, 6, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 85"
2, 0, Program_c, 1, 85
2, 0, Note_on_c, 1, 63, 60
2, 50, Note_off_c, 1, 63, 0
2, 50, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 91"
3, 0, Program_c, 2, 91
3, 0, Note_on_c, 2, 66, 60
3, 50, Note_off_c, 2, 66, 0
3, 50, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 91"
4, 0, Program_c, 3, 91
4, 0, Note_on_c, 3, 69, 60
4, 50, Note_off_c, 3, 69, 0
4, 50, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 91"
5, 0, Program_c, 4, 91
5, 0, Note_on_c, 4, 73, 60
5, 50, Note_off_c, 4, 73, 0
5, 50, End_track
6, 0, Start_track
6, 0, Instrument_name_t, "MIDI instrument 85"
6, 0, Program_c, 5, 85
6, 0, Note_on_c, 5, 39, 48
6, 200, Note_off_c, 5, 39, 0
6, 200, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox -D $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -r 256000 -b 32  $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 20 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.100 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
