#!/bin/bash -evx
# Copyright 2025 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

RATE=48000

# startup and shutdown es major
# Lists and texts: As major
# Messages: E major
# Areas: Des major

if [ "$1" != --no-old ]; then
    rm -f *.wav
    wget -q https://download.luwrain.org/compilation/sounds.tar.xz
    tar xf sounds.tar.xz
    mv sounds/schemes/pragmatic/*.wav .
    rm -rf sounds sounds.tar.xz
fi

./startup.sh
mv startup.wav _startup.wav
sox _startup.wav -r $RATE -b 16 -e signed-integer startup.wav gain -5

./shutdown.sh
mv shutdown.wav _shutdown.wav
sox _shutdown.wav -r $RATE -b 16 -e signed-integer shutdown.wav gain -5

./welcome.sh
mv welcome.wav _welcome.wav
sox _welcome.wav -r $RATE -b 16 welcome.wav gain -8


# Areas (Des major)

./area-layout.sh
mv area-layout.wav .area-layout.wav
sox .area-layout.wav -r $RATE -b 16 area-layout.wav gain -25

./area-layout-double.sh
mv area-layout-double.wav .area-layout-double.wav
sox -D .area-layout-double.wav -r $RATE -b 16 area-layout-double.wav gain -15

./area-layout-triple.sh
mv area-layout-triple.wav .area-layout-triple.wav
sox -D .area-layout-triple.wav area-layout-triple.wav gain -15

./popup.sh
mv popup.wav .popup.wav
sox -D .popup.wav -r $RATE -b 16 -e signed-integer popup.wav gain -20

./main-menu.sh
mv main-menu.wav _main-menu.wav
sox -D _main-menu.wav main-menu.wav gain -17.5

./main-menu-item.sh
mv main-menu-item.wav .main-menu-item.wav
sox -D .main-menu-item.wav main-menu-item.wav gain -30

# Messages

./message.sh
mv message.wav _message.wav
sox _message.wav -r $RATE -b 16 -e signed-integer message.wav gain -25

./error.sh
mv error.wav _error.wav
sox -D _error.wav -r $RATE -b 16 -e signed-integer error.wav gain -13

./done.sh
mv done.wav _done.wav
sox -D _done.wav done.wav gain -22

./inaccessible.sh
mv inaccessible.wav _inaccessible.wav
sox -D _inaccessible.wav -r $RATE -b 16 inaccessible.wav gain -25

# Clipboard

./copied.sh
mv copied.wav .copied.wav
sox -D .copied.wav -r $RATE -b 16 copied.wav gain  -20

./cut.sh
mv cut.wav _cut.wav
sox -D _cut.wav cut.wav gain  -20

./paste.sh
mv paste.wav _paste.wav
sox -D _paste.wav paste.wav gain  -20

# List and text navigation

./list-item.sh
mv list-item.wav _list-item.wav
sox -D _list-item.wav -r $RATE -b 16 list-item.wav gain  -12

./empty-line.sh
mv empty-line.wav .empty-line.wav
sox -D .empty-line.wav empty-line.wav gain  -22.5

./marked-list-item.sh
mv marked-list-item.wav .marked-list-item.wav
sox -D .marked-list-item.wav marked-list-item.wav gain  -25

./desktop-item.sh
mv desktop-item.wav .desktop-item.wav
sox -D .desktop-item.wav desktop-item.wav gain  -20

./bounds.sh
mv bounds.wav _bounds.wav
sox -D _bounds.wav bounds.wav gain -10

./no-content.sh
mv no-content.wav _no-content.wav
sox -D _no-content.wav no-content.wav gain -25



# misc

./commander-location.sh
mv commander-location.wav .commander-location.wav
sox -D .commander-location.wav commander-location.wav gain -22.5

rm -f _*.wav .*.wav


# For compatibility
#cp bounds.wav text-bounds.wav
for i in items-above items-below lines-above lines-below; do
    cp bounds.wav no-$i.wav
done
chmod 644 *.wav

cp *.wav ../core/src/main/resources/org/luwrain/core/sound
