#!/bin/bash -e

NAME=no-content

cat <<EOF > $NAME.csv
0, 0, Header, 1, 3, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 82"
2, 0, Program_c, 1, 82
2, 0, Note_on_c, 1, 56, 60
2, 170, Note_off_c, 1, 56, 0
2, 180, Note_on_c, 1, 56, 60
2, 350, Note_off_c, 1, 56, 0
2, 350, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 82"
3, 0, Program_c, 2, 82
3, 0, Note_on_c, 2, 63, 60
3, 170, Note_off_c, 2, 63, 0
3, 180, Note_on_c, 2, 63, 60
3, 350, Note_off_c, 2, 63, 0
3, 350, End_track
0, 0, End_of_file
EOF


csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox -D $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 20 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.100 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
