#!/bin/bash -e
# SPDX-License-Identifier: BUSL-1.1
# Copyright 2026 Michael Pozhidaev <msp@luwrain.org>

NAME=no-content

cat <<EOF > $NAME.csv
0, 0, Header, 1, 4, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 12"
2, 0, Program_c, 1, 12
2, 0, Note_on_c, 1, 56, 84
2, 100, Note_off_c, 1, 56, 0
2, 100, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 12"
3, 0, Program_c, 2, 12
3, 0, Note_on_c, 2, 60, 84
3, 100, Note_off_c, 2, 60, 0
3, 100, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 12"
4, 0, Program_c, 3, 12
4, 0, Note_on_c, 3, 63, 84
4, 100, Note_off_c, 3, 63, 0
4, 100, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -a -C 8 -s 256000   -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -e float $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav TREBLE 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav FADE t 0.1 2 1 .5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 75 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.1 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
