#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

NAME=popup

cat <<EOF > $NAME.csv
0, 0, Header, 1, 5, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 85"
2, 0, Program_c, 1, 85
2, 0, Note_on_c, 1, 77, 96
2, 70, Note_off_c, 1, 77, 0
2, 70, Note_on_c, 1, 78, 96
2, 140, Note_off_c, 1, 78, 0
2, 140, Note_on_c, 1, 75, 96
2, 210, Note_off_c, 1, 75, 0
2, 210, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 95"
3, 0, Program_c, 2, 95
3, 0, Note_on_c, 2, 49, 24
3, 700, Note_off_c, 2, 49, 0
3, 700, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 95"
4, 0, Program_c, 3, 95
4, 70, Note_on_c, 3, 53, 24
4, 770, Note_off_c, 3, 53, 0
4, 770, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 95"
5, 0, Program_c, 4, 95
5, 70, Note_on_c, 4, 56, 24
5, 770, Note_off_c, 4, 56, 0
5, 770, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -a -C 8 -s 256000 -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox $NAME.wav -c 1 -r 256000 -b 32 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -e float $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 50 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.100 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
