#!/bin/bash -e
# SPDX-License-Identifier: BUSL-1.1
# Copyright 2026 Michael Pozhidaev <msp@luwrain.org>

NAME=popup

cat <<EOF > $NAME.csv
0, 0, Header, 1, 6, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 70"
2, 0, Program_c, 1, 70
2, 0, Note_on_c, 1, 65, 84
2, 55, Note_off_c, 1, 65, 0
2, 55, Note_on_c, 1, 66, 84
2, 110, Note_off_c, 1, 66, 0
2, 110, Note_on_c, 1, 65, 84
2, 165, Note_off_c, 1, 65, 0
2, 165, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 32"
3, 0, Program_c, 2, 32
3, 0, Note_on_c, 2, 49, 120
3, 55, Note_off_c, 2, 49, 0
3, 55, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 95"
4, 0, Program_c, 3, 95
4, 0, Note_on_c, 3, 49, 36
4, 110, Note_off_c, 3, 49, 0
4, 110, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 95"
5, 0, Program_c, 4, 95
5, 0, Note_on_c, 4, 53, 36
5, 110, Note_off_c, 4, 53, 0
5, 110, End_track
6, 0, Start_track
6, 0, Instrument_name_t, "MIDI instrument 95"
6, 0, Program_c, 5, 95
6, 0, Note_on_c, 5, 56, 36
6, 110, Note_off_c, 5, 56, 0
6, 110, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -a -C 8 -s 256000 -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox $NAME.wav -c 1 -r 256000 -b 32 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -e float $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 70 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.1 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
