#!/bin/bash -e
# Copyright 2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

NAME=popup

cat <<EOF > $NAME.csv
0, 0, Header, 1, 5, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 85"
2, 0, Program_c, 1, 85
2, 0, Note_on_c, 1, 58, 60
2, 200, Note_off_c, 1, 58, 0
2, 200, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 85"
3, 0, Program_c, 2, 85
3, 50, Note_on_c, 2, 73, 60
3, 250, Note_off_c, 2, 73, 0
3, 250, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 85"
4, 0, Program_c, 3, 85
4, 50, Note_on_c, 3, 77, 60
4, 250, Note_off_c, 3, 77, 0
4, 250, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 10"
5, 0, Program_c, 4, 10
5, 60, Note_on_c, 4, 118, 54
5, 360, Note_off_c, 4, 118, 0
5, 360, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox -D $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -r 48000 $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 5 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 50 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.100 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
