#!/bin/bash -e

NAME=shutdown

cat <<EOF > $NAME.csv
0, 0, Header, 1, 5, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 32"
2, 0, Program_c, 1, 32
2, 0, Note_on_c, 1, 51, 60
2, 150, Note_off_c, 1, 51, 0
2, 150, Note_on_c, 1, 43, 48
2, 300, Note_off_c, 1, 43, 0
2, 300, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 91"
3, 0, Program_c, 2, 91
3, 320, Note_on_c, 2, 51, 48
3, 370, Note_off_c, 2, 51, 0
3, 370, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 91"
4, 0, Program_c, 3, 91
4, 320, Note_on_c, 3, 67, 48
4, 370, Note_off_c, 3, 67, 0
4, 370, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 91"
5, 0, Program_c, 4, 91
5, 320, Note_on_c, 4, 70, 48
5, 370, Note_off_c, 4, 70, 0
5, 370, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox -D $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -r 48000 $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 10 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 65 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.100 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
