#!/bin/bash -e
# SPDX-License-Identifier: BUSL-1.1
# Copyright 2012-2025 Michael Pozhidaev <msp@luwrain.org>



NAME=startup

cat <<EOF > $NAME.csv
0, 0, Header, 1, 5, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 88"
2, 0, Program_c, 1, 88
2, 0, Note_on_c, 1, 75, 48
2, 120, Note_off_c, 1, 75, 0
2, 120, Note_on_c, 1, 74, 36
2, 240, Note_off_c, 1, 74, 0
2, 240, Note_on_c, 1, 70, 36
2, 360, Note_off_c, 1, 70, 0
2, 360, Note_on_c, 1, 63, 36
2, 480, Note_off_c, 1, 63, 0
2, 480, Note_on_c, 1, 58, 42
2, 600, Note_off_c, 1, 58, 0
2, 600, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 32"
3, 0, Program_c, 2, 32
3, 0, Note_on_c, 2, 51, 60
3, 100, Note_off_c, 2, 51, 0
3, 100, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 29"
4, 0, Program_c, 3, 29
4, 520, Note_on_c, 3, 39, 42
4, 5520, Note_off_c, 3, 39, 0
4, 5520, End_track
5, 0, Start_track
5, 0, Instrument_name_t, "MIDI instrument 32"
5, 0, Program_c, 4, 32
5, 480, Note_on_c, 4, 51, 96
5, 680, Note_off_c, 4, 51, 0
5, 680, Note_on_c, 4, 39, 96
5, 880, Note_off_c, 4, 39, 0
5, 880, Note_on_c, 4, 27, 96
5, 1080, Note_off_c, 4, 27, 0
5, 1080, Note_on_c, 4, 39, 66
5, 1280, Note_off_c, 4, 39, 0
5, 1280, Note_on_c, 4, 27, 66
5, 1780, Note_off_c, 4, 27, 0
5, 1780, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -a -C 8 -s 256000   -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -e float $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 3 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav FADE t 0.1 4 3  && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 75 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.1 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
