#!/bin/bash -e

NAME=startup

cat <<EOF > $NAME.csv
0, 0, Header, 1, 4, 480
1, 0, Start_track
1, 0, Title_t, "proba"
1, 0, Text_t, "Generated by LUWRAIN Cloud"
1, 0, Copyright_t, "UNKNOWN"
1, 0, Time_signature, 4, 2, 24, 8
1, 0, Tempo, 500000
1, 0, End_track
2, 0, Start_track
2, 0, Instrument_name_t, "MIDI instrument 93"
2, 0, Program_c, 1, 93
2, 0, Note_on_c, 1, 75, 60
2, 120, Note_off_c, 1, 75, 0
2, 120, Note_on_c, 1, 74, 48
2, 240, Note_off_c, 1, 74, 0
2, 240, Note_on_c, 1, 70, 48
2, 360, Note_off_c, 1, 70, 0
2, 360, Note_on_c, 1, 63, 48
2, 480, Note_off_c, 1, 63, 0
2, 480, Note_on_c, 1, 58, 72
2, 600, Note_off_c, 1, 58, 0
2, 600, End_track
3, 0, Start_track
3, 0, Instrument_name_t, "MIDI instrument 32"
3, 0, Program_c, 2, 32
3, 480, Note_on_c, 2, 51, 60
3, 680, Note_off_c, 2, 51, 0
3, 680, Note_on_c, 2, 39, 48
3, 980, Note_off_c, 2, 39, 0
3, 980, Note_on_c, 2, 15, 36
3, 1480, Note_off_c, 2, 15, 0
3, 1480, End_track
4, 0, Start_track
4, 0, Instrument_name_t, "MIDI instrument 85"
4, 0, Program_c, 3, 85
4, 0, Note_on_c, 3, 51, 48
4, 100, Note_off_c, 3, 51, 0
4, 100, End_track
0, 0, End_of_file
EOF

csvmidi < $NAME.csv > $NAME.midi && rm -f $NAME.csv
timidity -Ow $NAME.midi > /dev/null && rm -f $NAME.midi
sox -D $NAME.wav -c 1 .$NAME.wav && rm -f $NAME.wav && sox -D .$NAME.wav -c 2 -r 48000 $NAME.wav && rm -f .$NAME.wav
sox -D $NAME.wav .$NAME.wav BASS 10 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D $NAME.wav .$NAME.wav REVERB 65 && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
sox -D --norm=-0.100 $NAME.wav .$NAME.wav && rm -f $NAME.wav && mv .$NAME.wav $NAME.wav
