#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

WIN_EXTENSIONS='mssapi plmp3 rhvoice'
WIN_PROPERTIES='luwrain reader windows'

JAVAFX_VER=17

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1
mkdir -p "$DEST_DIR"

cp -r release/jar "$DEST_DIR"
cp release/lib/*.jar "$DEST_DIR/jar"
mkdir -p "$DEST_DIR/data"
cp -r extensions/js "$DEST_DIR/data/js"
cd "$DEST_DIR"

pushd jar > /dev/null
rm -f luwrain-linux*.jar
rm -f javafx-*-linux.jar
for i in base controls graphics media swing web; do
    wget -q https://repo1.maven.org/maven2/org/openjfx/javafx-$i/$JAVAFX_VER/javafx-$i-$JAVAFX_VER-win.jar
done
popd > /dev/null

pushd data > /dev/null
for i in sounds hunspell; do
    wget -q https://download.luwrain.org/compilation/$i.tar.xz
    tar xf $i.tar.xz
    rm -f $i.tar.xz
done
rm -rf sounds/schemes
popd > /dev/null

#Jars
find "$SRC_DIR/." -name 'luwrain-app-*.jar' -exec cp '{}' jar \;
for i in $LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $WIN_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

#Registry
pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile win "$DEST_DIR/data"
popd > /dev/null

#Properties
mkdir data/properties
for i in $WIN_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties
luwrain.version = $VERSION
luwrain.registry.version = $REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

#luwrain.bat
cat <<EOF > luwrain.bat
rem Runs LUWRAIN with the locally installed (not embedded) JRE

javaw -cp jar\luwrain-base.jar
EOF
