#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

[ -z "$1" ] && echo "ERROR: $THIS: No app name" >&2 && exit 1
APP_NAME="$1"

cat <<EOF
<project name="luwrain-app-$APP_NAME" default="jar" basedir=".">
  <path id="classpath">
    <pathelement location="."/>
    <fileset dir="../release/lib"><include name="**/*.jar"/></fileset>
    <fileset dir="../release/jar"><include name="**/*.jar"/></fileset>
  </path>
  <path id="mainjar">
    <pathelement location="."/>
    <fileset dir="jar"><include name="**/*.jar"/></fileset>
  </path>
  <target name="clean">
    <delete dir="build"/>
    <delete dir="jar"/>
    <delete dir="target"/>
  </target>
  <target name="compile" depends="clean">
    <mkdir dir="build"/>
    <mkdir dir="build/main"/>
    <javac includeantruntime="false" encoding="UTF-8" srcdir="src/main/java" destdir="build/main" source="$JAVA_VERSION" target="$JAVA_VERSION" debug="true" debuglevel="lines,vars,source">
      <classpath refid="classpath"/>
      <compilerarg value="-Xlint:unchecked" />
      <compilerarg value="-Xlint:deprecation" />
      <compilerarg value="-Xlint:-options"/>
    </javac>
  </target>
  <target name="jar" depends="compile">
    <mkdir dir="jar"/>
    <jar jarfile="jar/luwrain-app-$APP_NAME.jar">
      <manifest>
        <section name="org/luwrain">
          <attribute name="Extensions" value="org.luwrain.app.$APP_NAME.Extension"/>
        </section>
      </manifest>
      <fileset dir="./build/main">
        <include name="**/*.class"/>
      </fileset>
      <fileset dir="./src/main/resources">
        <include name="**/*"/>
      </fileset>
    </jar>
  </target>
    <target name="compile-test" depends="jar">
    <mkdir dir="build"/>
    <mkdir dir="build/test"/>
    <javac srcdir="src/test/java" destdir="build/test" source="1.8" target="1.8">
      <classpath>
        <path refid="classpath"/>
        <path refid="mainjar"/>
      </classpath>
    </javac>
  </target>
  <target name="jar-test" depends="compile-test">
    <jar jarfile="jar/luwrain-app-$APP_NAME-test.jar">
      <fileset dir="./build/test">
        <include name="**/*.class"/>
      </fileset>
    </jar>
  </target>
  <target name="junit" depends="jar-test">
    <junit printsummary="withOutAndErr">
      <classpath>
        <path refid="classpath"/>
        <path refid="mainjar"/>
      </classpath>
      <formatter type="xml" usefile="true" />
      <batchtest fork="yes">
        <fileset dir="build/test">
          <include name="**/*Test.class"/>
        </fileset>
      </batchtest>
    </junit>
  </target>
</project>
EOF
