#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

lwr-ant-gen-all
lwr-build-mvn

for i in $APPS; do
    pushd app-$i > /dev/null
    if [ -r build.gradle ]; then
	lwr-install-gradle-wrapper "$(pwd)"
	./gradlew build
    else
	ant -emacs -quiet
    fi
   popd > /dev/null
done

pushd extensions > /dev/null
for i in $EXTENSIONS; do
    pushd $i > /dev/null
    ant -emacs -quiet
    popd > /dev/null
done
popd > /dev/null

pushd i18n > /dev/null
for i in $LANGS; do
    pushd $i > /dev/null
    ant -emacs -quiet
popd > /dev/null
done
popd > /dev/null

echo Everything is built successfully!
