#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

MODULES="base luwrain io reader pim studio interaction-javafx browser linux player windows"

. init.sh

for i in $MODULES; do
    rm -rf $i/target
done
rm -rf target release

mvn install -B -C -q
mkdir -p release/lib
for i in base/target/lib/*.jar; do
    cat $i > release/lib/"$(basename "$i")"
done
mkdir release/jar
for i in $MODULES; do
    cp $i/target/*.jar release/jar
done

pushd release > /dev/null
mkdir sources javadoc
mv jar/*sources*.jar sources
mv jar/*javadoc*.jar javadoc
mv lib/luwrain*.jar jar
popd > /dev/null

#cp -r lib/. release/lib
