#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

DEST_DIR=/tmp/lwr-jre

rm -rf -- "$DEST_DIR"

jlink --output="$DEST_DIR" --no-header-files --no-man-pages --module-path=/opt/jmod --add-modules=\
java.scripting,\
jdk.scripting.nashorn,\
javafx.base,\
javafx.fxml,\
javafx.swing,\
javafx.controls,\
javafx.graphics,\
javafx.media,\
javafx.web

du -s -m "$DEST_DIR"

