#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

rm -rf release
rm -rf */target */jar  */build

cd i18n
rm -rf */build */jar

cd ../extensions
rm -rf */build */jar
