#!/bin/bash -e

. init.sh

[ -z "$1" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1
DEST_DIR="$1"
mkdir -p "$DEST_DIR"
lwr-dist-linux "$DEST_DIR"
lwr-dist-win "$DEST_DIR"
pushd "$DEST_DIR/win-installer-x64" > /dev/null
docker run --rm -i -v "$(pwd):/work" innosetup Luwrain.iss
popd > /dev/null

pushd "$DEST_DIR" > /dev/null
mv win-installer-x64/Output/luwrain.exe "luwrain-windows-x64-$VERSION.exe"
rm -rf win-installer-x64
sha1sum "luwrain-windows-x64-$VERSION.exe" >> sha1.txt
popd > /dev/null
