#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

FLAVOR="$1"
ARCH="$2"
DIST_DIR="$3"
DEST_DIR="$4"
[ -z "$FLAVOR" ] && echo "$THIS: no flavor" >&2 && exit 1
[ -z "$ARCH" ] && echo "$THIS: no arch" >&2 && exit 1
[ -z "$DIST_DIR" ] && echo "$THIS: no source dir" >&2 && exit 1
[ -z "$DEST_DIR" ] && echo "$THIS: no dest dir" >&2 && exit 1

mkdir -p "$DEST_DIR"
cd "$DEST_DIR"

wget -q https://download.luwrain.org/compilation/InnoSetup.tar.xz
tar xf InnoSetup.tar.xz
rm -f InnoSetup.tar.xz

# Copying the source distribution
cp -r "$DIST_DIR" Luwrain

# Copying the scripts and configs for building of installer
cp -r "$SRC_DIR/windows/installer/$FLAVOR/." ./
iconv -t cp1251 -o Luwrain.new Luwrain.iss
rm -f Luwrain.iss
mv Luwrain.new Luwrain.iss
sed -i -e s/LUWRAIN_VERSION/$VERSION/ Luwrain.iss
cp "$SRC_DIR/windows/installer/run.bat" .
sed -i -e s/LUWRAIN_INSTALLER_ARCH/$ARCH/ run.bat
