#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

cat <<EOF > debian/changelog
luwrain ($(date +%Y%m%d.%H%M)-lwr1) unstable; urgency=medium

  * The package for Debian

 -- Michael Pozhidaev <msp@luwrain.org>  $(LANG=C date '+%a, %d %b %Y %X %z')
EOF


sed -i -e s/'Package: luwrain'/'Package: luwrain-snapshot'/ debian/control
