#!/bin/bash -e

. init.sh

[ -z "$1" ] && echo "ERROR: $THIS: No component" >&2 && exit 1
COMPONENT="$1"

if [ "$COMPONENT" != luwrain ]; then
    NAME="luwrain-$COMPONENT"
else
    NAME=luwrain
fi

cd "$SRC_DIR/$COMPONENT"

mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file \
    -Dfile=pom.xml \
    -DgroupId=$GROUP -DartifactId=$NAME -Dversion=$VERSION \
    -Dpackaging=pom -DcreateChecksum=true -DgeneratePom=false \
    -DlocalRepositoryPath="$MAVEN_REPO_DIR" -B -q

for i in javadoc sources; do
    mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file \
	-Dfile=target/$NAME-$VERSION-$i.jar \
	-DgroupId=$GROUP -DartifactId=$NAME -Dversion=$VERSION \
	-Dpackaging=jar -DcreateChecksum=true -DgeneratePom=false -Dclassifier=$i \
	-DlocalRepositoryPath="$MAVEN_REPO_DIR" -B -q
done

mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file \
    -Dfile=target/$NAME-$VERSION.jar \
    -DgroupId=$GROUP -DartifactId=$NAME -Dversion=$VERSION \
    -Dpackaging=jar -DcreateChecksum=true -DgeneratePom=false \
    -DlocalRepositoryPath="$MAVEN_REPO_DIR" -B -q

