#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

LINUX_EXTENSIONS='cmdtts emacspeak plmp3 rhvoice speechd voiceman'
LINUX_SCRIPTS='linux'
LINUX_PROPERTIES='linux luwrain reader'

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1
mkdir -p "$DEST_DIR/data"
cp -r release/jar "$DEST_DIR"
cp release/lib/*.jar "$DEST_DIR/jar"
cp -r extensions/js "$DEST_DIR/data/js"
cd "$DEST_DIR"

pushd data > /dev/null
for i in sounds hunspell; do
    wget -q https://download.luwrain.org/compilation/$i.tar.xz
    tar xf $i.tar.xz
    rm -f $i.tar.xz
done
rm -rf sounds/schemes
popd > /dev/null

#Jars
find "$SRC_DIR/." -name 'luwrain-app-*.jar' -exec cp '{}' jar \;
for i in $LANGS; do
    cp "$SRC_DIR"/i18n/$i/jar/luwrain-lang-$i.jar jar
done
for i in $LINUX_EXTENSIONS; do
    cp "$SRC_DIR"/extensions/$i/jar/luwrain-ext-$i.jar jar
done

#Registry
pushd "$SRC_DIR/registry" > /dev/null
./lwr-reg-compile linux "$DEST_DIR/data"
popd > /dev/null

#Properties
mkdir data/properties
for i in $LINUX_PROPERTIES; do
    cp -r "$SRC_DIR/$i/properties/." data/properties
done
cat <<EOF > data/properties/release.properties
luwrain.version = $VERSION
luwrain.registry.version = $REGISTRY_VERSION
luwrain.build.date = $(date -I)
EOF

#Scripts
mkdir -p data/scripts
for i in $LINUX_SCRIPTS; do
    cp -r "$SRC_DIR/$i/scripts/." data/scripts
done
chmod +x data/scripts/*
