#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

JRE=jre18-win-x64
ARCH=x64

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1

mkdir -p $DEST_DIR
cd $DEST_DIR

wget -q https://download.luwrain.org/compilation/$JRE.tar.xz
tar xf $JRE.tar.xz
mv $JRE $ARCH
rm -f $JRE.tar.xz

wget -q https://download.luwrain.org/compilation/rhvoice-data.tar.xz
tar xf rhvoice-data.tar.xz
cp -r rhvoice $ARCH/rhvoice
rm -rf rhvoice*

cd $ARCH
lwr-basedirs-win $DEST_DIR/$ARCH
cat <<EOF > ReleaseInfo.txt
LUWRAIN $VERSION ($(date -I))
$ARCH release for Microsoft Windows
EOF
cd ..

lwr-win-installer luwrain 64 $DEST_DIR/$ARCH $DEST_DIR/win-installer-$ARCH
mv "$ARCH" luwrain-windows-portable-"$ARCH"-"$VERSION"
zip -r luwrain-windows-portable-"$ARCH"-"$VERSION".zip luwrain-windows-portable-"$ARCH"-"$VERSION" > /dev/null
sha1sum luwrain-windows-portable-"$ARCH"-"$VERSION".zip >> sha1.txt
rm -rf luwrain-windows-portable-"$ARCH"-"$VERSION"

