#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DEST_DIR=/tmp/lwr-jdk-runtime
rm -rf "$DEST_DIR"

list-standard()
{
cat "$SRC_DIR/base/jdk/jmods"
#find /opt/jdk/ -iname '*.jmod' | while read l; do
#basename "$l" | sed s/'.jmod'/''/
#done
}

JMODS=$(list-standard | xargs | sed s/' '/','/g)

jlink -p /opt/jfx-jmods --add-modules $JMODS --output "$DEST_DIR"
