#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

lwr-list-repos | while read l; do
    pushd "$SRC_DIR/$l"
    git fsck --full
    echo Checked
    git gc

    popd > /dev/null
done
