#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

SRC_DEST_DIR="$1"
[ -z "$SRC_DEST_DIR" ] && echo "ERROR: $THIS: No destination directory" >&2 && exit 1
[ -e "$SRC_DEST_DIR" ] && echo "$THIS:$SRC_DEST_DIR already exists" >&2 && exit 1

mkdir -p "$SRC_DEST_DIR"
cp -r . "$SRC_DEST_DIR"

for i in AUTHORS LICENSE; do
find "$SRC_DEST_DIR" -name $i -delete
done

for i in AUTHORS LICENSE; do
    cp luwrain/$i "$SRC_DEST_DIR"
done
cp base/txt/src/* "$SRC_DEST_DIR"

cd "$SRC_DEST_DIR"
rm -rf debian .git*
ls | while read l; do
    if [ -e "$l/.git" ]; then
rm -rf "$l/.git"
fi
done
find -name .gitignore -delete
