#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

DEST_DIR="$1"
[ -z "$DEST_DIR" ] && echo "$THIS: no destination directory" >&2 && exit 1

rm -rf "$DEST_DIR"
mkdir -p "$DEST_DIR"
cd "$DEST_DIR"

lwr-basedirs-linux "$DEST_DIR/"

pushd jar > /dev/null
rm -f javafx-*.jar rhvoice*.jar bridj*.jar hunspell*.jar
mv luwrain-base-*.jar luwrain-base.jar
for i in bridj.jar hunspell.jar rhvoice-1.2.3-jni.jar; do
    wget -q https://download.luwrain.org/compilation/rp4/$i
done
popd > /dev/null

cat <<EOF > luwrain
#!/bin/bash -e
# Runs the LUWRAIN platform
# Copyright 2022 Michael Pozhidaev <msp@luwrain.org>

export NO_AT_BRIDGE=1

cd /opt/luwrain
exec java --module-path /usr/share/openjfx/lib --add-modules javafx.controls -jar jar/luwrain-base.jar --lang=ru --speech=voiceman "\$@"
EOF
chmod 755 luwrain


