#!/bin/bash -e
# Copyright 2012-2024 Michael Pozhidaev <msp@luwrain.org>
# The LUWRAIN Project, GPL v.3

. init.sh

TAG="$1"
[ -z "$TAG" ] && echo "$THIS: No tag" >&2 && exit 1

lwr-list-repos | while read l; do
    echo "Tagging $l"
    pushd $l  > /dev/null
    git tag "$TAG" > /dev/null
    git push --tags origin > /dev/null
    popd		 > /dev/null
done			
