services:
  jenkins:
    build: .
    container_name: jenkins
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /jenkins/src:/var/jenkins_home/workspace/luwrain/
      - /jenkins/out:/out/
      - /jenkins/certs:/certs
      - /jenkins/build:/build
      - /jenkins/cache:/cache

  dind:
    image: docker:dind
    container_name: docker
    privileged: true
    restart: always
    volumes:
      - /jenkins/certs:/certs
      - /jenkins/build:/build
      - /jenkins/cache:/cache
