#!/bin/bash

#sleep 60

pactl set-sink-mute @DEFAULT_SINK@ 0



#export WLR_NO_HARDWARE_CURSORS=1
#export LIBGL_ALWAYS_SOFTWARE=1

#export WLR_DRM_NO_MODIFIERS=1


exec >> /tmp/sway.log 2>&1
#echo XDG $XDG_RUNTIME_DIR
#ls $XDG_RUNTIME_DIR

#export WLR_NO_HARDWARE_CURSORS=1
#export WLR_RENDERER=gles2


eval $(dbus-launch --sh-syntax)

export WLR_BACKENDS=headless
export WLR_RENDERER=pixman

echo Starting sway
sway -V "$@"
echo Exit code $?
while /bin/true; do
    sleep 10
done
