#!/bin/bash -evx

cd /iso
. base.sh
apt-get --yes install squashfs-tools xorriso

mksquashfs chroot disk/casper/filesystem.squashfs -comp xz > /dev/null

rm -rf disk/casper/filesystem.squashfs.gpg disk/md5sum.txt disk/pool disk/ubuntu 
echo "LUWRAIN $LWRISO_VERSION Release $LWRISO_ARCH ($LWRISO_DATE)" > disk/.disk/info

cat <<EOF > disk/README.ru.txt
Платформа невизуальных приложений LUWRAIN
Версия: $LWRISO_VERSION
Дата релиза: $(date '+%d.%m.%Y')
Основано на: Ubuntu $LWRISO_BOOT_VER ($LWRISO_ARCH)

Описание установки на компьютер смотрите в документации по адресу https://luwrain.org/doc/user/installation/iso/
EOF

pushd disk > /dev/null
#find -type f '!' -name isolinux.bin '!' -name boot.cat | while read l; do
find -type f '!' -name boot.catalog '!' -name eltorito.img | while read l; do
md5sum "$l"
done > ../md5sum.txt
popd  > /dev/null
mv md5sum.txt disk

wget -q "https://download.luwrain.org/compilation/ubuntu-amd64-$LWRISO_BOOT_VER.efi"
wget -q "https://download.luwrain.org/compilation/ubuntu-amd64-$LWRISO_BOOT_VER.mbr"

mv "ubuntu-amd64-$LWRISO_BOOT_VER.efi" ubuntu.efi
mv "ubuntu-amd64-$LWRISO_BOOT_VER.mbr" ubuntu.mbr

xorriso -as mkisofs \
  -r -V "LUWRAIN $LWRISO_ARCH $(date --iso-8601)" -J -joliet-long -l \
  -iso-level 3 \
  -partition_offset 16 \
  --grub2-mbr ubuntu.mbr \
  --mbr-force-bootable \
  -append_partition 2 0xEF ubuntu.efi \
  -appended_part_as_gpt \
  -c /boot.catalog \
  -b /boot/grub/i386-pc/eltorito.img \
    -no-emul-boot -boot-load-size 4 -boot-info-table --grub2-boot-info \
  -eltorito-alt-boot \
  -e '--interval:appended_partition_2:all::' \
    -no-emul-boot \
  -o luwrain.iso \
  disk/
