Document: voiceman
Title: Debian voiceman Manual
Author: <insert document author here>
Abstract: This manual describes what voiceman is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/voiceman/voiceman.sgml.gz

Format: postscript
Files: /usr/share/doc/voiceman/voiceman.ps.gz

Format: text
Files: /usr/share/doc/voiceman/voiceman.text.gz

Format: HTML
Index: /usr/share/doc/voiceman/html/index.html
Files: /usr/share/doc/voiceman/html/*.html
