Document: freespeech
Title: Debian freespeech Manual
Author: <insert document author here>
Abstract: This manual describes what freespeech is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freespeech/freespeech.sgml.gz

Format: postscript
Files: /usr/share/doc/freespeech/freespeech.ps.gz

Format: text
Files: /usr/share/doc/freespeech/freespeech.text.gz

Format: HTML
Index: /usr/share/doc/freespeech/html/index.html
Files: /usr/share/doc/freespeech/html/*.html
