#!/bin/bash -e
# Ilia Paschuk <ilusha.paschuk@gmail.com>
# Alexander Panshin <alexanderpanshin@gmail.com>
# Michael Pozhidaev <msp@luwrain.org>

USER=luwrain

curl -s https://download.luwrain.org/gpg/dpkg.gpg.pub | apt-key add -
cat <<EOF > /etc/apt/sources.list.d/luwrain.list
deb https://download.luwrain.org/repo/ luwrain bullseye
EOF

apt-get update
apt-get install --yes  voiceman mbrola-suite rhvoice-legacy dwm-luwrain locales-all xserver-xorg-video-dummy mplayer network-manager bluez-tools cryptsetup
apt-get remove --yes  openresolv dhcpcd5

mkdir /etc/luwrain
cat <<EOF > /etc/luwrain/system-start
#!/bin/bash -e
# Starts LUWRAIN as a regular user

USER=$USER

bt-agent -d --capability=NoInputNoOutput 
/bin/su - \$USER -c /usr/bin/startx
EOF
chmod 755 /etc/luwrain/system-start

systemctl set-default multi-user.target
mkdir -p /etc/systemd/system/getty@tty1.service.d
cat <<EOF > /etc/systemd/system/getty@tty1.service.d/override.conf
[Service]
Environment="LANG=en_US.UTF-8"
ExecStart=
ExecStart=-/bin/openvt -c 1 -w -s -f /etc/luwrain/system-start
Type=idle
EOF
pushd /etc/systemd > /dev/null
sed -i -e s/'^.*NAutoVTs.*$'/'NAutoVTs=0'/  logind.conf
popd > /dev/null
systemctl enable getty@tty1

mkdir -p /etc/voiceman.d
rm -rf /etc/voiceman.d/*
cp *.output /etc/voiceman.d
cat voiceman.conf > /etc/voiceman.conf

cat xorg.conf > /etc/X11/xorg.conf
cat xinitrc > /home/$USER/.xinitrc
chown $USER:$USER /home/$USER/.xinitrc

cat dwm-autolaunch > /usr/local/bin/dwm-autolaunch
chmod 755 /usr/local/bin/dwm-autolaunch

cat <<EOF > /etc/asound.conf
pcm.!default {
    type pulse
}

ctl.!default {
    type pulse
}
EOF

cd /etc/java-*-openjdk
cat <<EOF >> sound.properties

javax.sound.sampled.Clip=com.sun.media.sound.DirectAudioDeviceProvider
javax.sound.sampled.Port=com.sun.media.sound.PortMixerProvider
javax.sound.sampled.SourceDataLine=com.sun.media.sound.DirectAudioDeviceProvider
javax.sound.sampled.TargetDataLine=com.sun.media.sound.DirectAudioDeviceProvider
EOF

cd /etc/pulse
echo 'load-module module-switch-on-connect' >> default.pa

cp aliases /home/luwrain/.bash_aliases
chown luwrain:luwrain /home/luwrain/.bash_aliases

# removing vlc-bin vlc-data

